[package]
name = "fb2server"
version = "0.1.0"
edition = "2021"


[dependencies]
    anyhow = "1.0"
    actix-web = "4.2"
    log = "0.4"
    env_logger = "0.9"
    quick-xml = "0.26.0"
    chrono = "0.4"
